title: Emily Esten
author: eastofesten
email: estenemily+website@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Personal website of Emily Esten
show_excerpts: false # set to true to show excerpts on the homepage
url: "https://emilyesten.com"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Emily Esten
  tagline: digital projects for the public
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: CV
      url: "/assets/files/esten-cv.pdf"
  showPicker: false

  # generate social links in footer
  social_links:
    github:  eastofesten
    linkedIn: in/emilyesten
    bsky: estene.bsky.social
    arts: "https://www.broadstreetreview.com/about/people/emily-esten"
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed